"""
index_manager.py — Knowledge asset index management

Maintains store/index/assets.yaml as a machine-readable manifest of all
knowledge assets in the store. The index is derived from the asset files
and can always be regenerated by scanning the assets directory.

Capability: CAP-001 (Knowledge Management)
Defined by: ADR-003 — Knowledge Persistence Approach
"""

import os
import re
from datetime import date
from pathlib import Path
from typing import Optional

import frontmatter
import yaml

STORE_DIR = Path(__file__).parent.parent / "store"
ASSETS_DIR = STORE_DIR / "assets"
INDEX_FILE = STORE_DIR / "index" / "assets.yaml"

ASSET_ID_PATTERN = re.compile(r"^KA-(\d+)$")


def _asset_files() -> list[Path]:
    """Return all .md files under the assets directory."""
    return sorted(ASSETS_DIR.rglob("*.md"))


def _domain_for(path: Path) -> str:
    """Return the domain name (parent directory name) for an asset file."""
    return path.parent.name


def _read_index() -> dict:
    if not INDEX_FILE.exists():
        return {"assets": []}
    with INDEX_FILE.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    if "assets" not in data:
        data["assets"] = []
    return data


def _write_index(data: dict) -> None:
    INDEX_FILE.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Knowledge Asset Index\n"
        "#\n"
        "# Auto-generated by platform/knowledge/src/cli.py index rebuild\n"
        "# DO NOT edit manually — regenerate with: python src/cli.py index rebuild\n"
        "#\n"
        f"# Last rebuilt: {date.today().isoformat()}\n\n"
    )
    with INDEX_FILE.open("w", encoding="utf-8") as f:
        f.write(header)
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def rebuild_index() -> int:
    """Scan all asset files and rebuild the index. Returns the number of assets indexed."""
    assets = []
    for path in _asset_files():
        try:
            post = frontmatter.load(str(path))
            meta = post.metadata
            entry = {
                "id": meta.get("id", ""),
                "title": meta.get("title", path.stem),
                "status": meta.get("status", "draft"),
                "domain": _domain_for(path),
                "path": str(path.relative_to(STORE_DIR.parent)),
                "version": meta.get("version", 1),
                "updated": str(meta.get("updated", "")),
            }
            assets.append(entry)
        except Exception as exc:
            # Log but do not abort — a single malformed file should not break the index
            print(f"Warning: could not parse {path}: {exc}")

    # Sort by ID for stable output
    assets.sort(key=lambda e: e["id"])
    _write_index({"assets": assets})
    return len(assets)


def next_asset_id() -> str:
    """Return the next available KA-NNN identifier."""
    max_n = 0
    # Use the index as the primary source (fast)
    index = _read_index()
    for entry in index.get("assets", []):
        m = ASSET_ID_PATTERN.match(entry.get("id", ""))
        if m:
            max_n = max(max_n, int(m.group(1)))
    # Also scan asset files so we don't collide if the index is stale
    for path in _asset_files():
        try:
            post = frontmatter.load(str(path))
            m = ASSET_ID_PATTERN.match(post.metadata.get("id", ""))
            if m:
                max_n = max(max_n, int(m.group(1)))
        except Exception:
            continue
    return f"KA-{max_n + 1:03d}"


def find_by_id(asset_id: str) -> Optional[Path]:
    """Return the file path for a given asset ID, or None if not found."""
    for path in _asset_files():
        try:
            post = frontmatter.load(str(path))
            if post.metadata.get("id") == asset_id:
                return path
        except Exception:
            continue
    return None


def get_all_entries() -> list[dict]:
    """Return all entries from the index."""
    return _read_index().get("assets", [])


def add_or_update_entry(asset_id: str, entry: dict) -> None:
    """Add or update a single entry in the index without a full rebuild."""
    data = _read_index()
    assets = data.get("assets", [])
    for i, existing in enumerate(assets):
        if existing.get("id") == asset_id:
            assets[i] = entry
            break
    else:
        assets.append(entry)
    assets.sort(key=lambda e: e["id"])
    data["assets"] = assets
    _write_index(data)
